CREATE DATABASE IF NOT EXISTS companydb;
USE companydb;

CREATE TABLE IF NOT EXISTS Employee (
  EmpID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Salary DECIMAL(10,2) NOT NULL
);

INSERT INTO Employee (Name, Salary) VALUES
('Amit Sharma', 45000.00),
('Neha Verma', 52000.00),
('Rajat Singh', 60000.00);

CREATE TABLE IF NOT EXISTS Attendance (
  id INT PRIMARY KEY AUTO_INCREMENT,
  studentId VARCHAR(50) NOT NULL,
  attendDate DATE NOT NULL,
  status VARCHAR(10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
